spring.application.name=tic-tac-toe-backend
server.port=8081
ai-catalog-api.url=http://localhost:8000/api/tic-tac-toe
game-state-service.ai-uuid=0e5ce7dd-c39c-4475-a52c-c0b85edd2074

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres?currentSchema=tictactoe
spring.datasource.username=user
spring.datasource.password=password

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:sql/data.sql

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/FourteenGames
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/FourteenGames/protocol/openid-connect/certs

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

spring.rabbitmq.fourteengames.exchange-name=xivgames_exchange
spring.rabbitmq.fourteengames.register-game-binding=game.register
spring.rabbitmq.fourteengames.register-game-queue=register_game
spring.rabbitmq.fourteengames.unlock-achievement-binding=achievement.unlock

spring.game.registration.id=19dd9398-0b25-4049-abe3-0a8577b0fd8e
spring.game.registration.name=Tic Tac Toe
spring.game.registration.max-players=2
#spring.game.registration.ai-start-game-endpoint=http://localhost:8081/tic-tac-toe/api/matches/ai
spring.game.registration.start-game-endpoint=http://localhost:8081/tic-tac-toe/api/matches
spring.game.registration.description=A classic 2-player strategy game.
spring.game.registration.price=19.98
spring.game.registration.image=tictactoe.png
spring.game.registration.icon=https://www.svgrepo.com/show/143264/tic-tac-toe-game.svg
spring.game.registration.genre=Strategy

spring.game.registration.internal-game-url=http://localhost:5174/gamehosts/tic-tac-toe/
spring.game.registration.external-game-url=http://localhost:5174/gamehosts/tic-tac-toe/

cors.allowed-origins=http://localhost:5173,http://localhost:5174