@user1=b85182a8-68f8-4d42-b0d5-6166bf2e8284
@user2=7ad223bd-bf5e-4945-8284-3a9c81e4e7a9

@ClientId=TTT-backend
@ClientSecret=YjKubFkS8JKWJDlMMaXPr0UPrSXbiRHi
@player1username=123
@player1password=123

### Get access token for player1
POST http://localhost:8180/realms/FourteenGames/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{ClientId}}&client_secret={{ClientSecret}}&username={{player1username}}&password={{player1password}}&grant_type=password&scope=openid

> {%
    client.global.set("access_token", response.body.access_token);
%}


### Starting a new match between player 1 and player 2
POST http://localhost:8081/tic-tac-toe/api/matches
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "player1Id": "{{user1}}",
  "player2Id": "{{user2}}"
}

> {%
    client.global.set("gameId", response.body.id);
%}

### starting a new match against an ai
POST http://localhost:8081/tic-tac-toe/api/matches/ai
Content-Type: application/json
Authorization: Bearer {{access_token}}

> {%
    client.global.set("gameId", response.body.id);
%}

### getting match
GET http://localhost:8081/tic-tac-toe/api/matches/{{gameId}}

### let the Ai move
PATCH http://localhost:8081/tic-tac-toe/api/matches/{{gameId}}/ai

### making a move
PATCH http://localhost:8081/tic-tac-toe/api/matches/{{gameId}}
Content-Type: application/json

{
  "x": 0,
  "y": 1,
  "player": "{{user1}}"
}

### making a counter move
PATCH http://localhost:8081/tic-tac-toe/api/matches/{{gameId}}
Content-Type: application/json

{
  "x": 1,
  "y": 2,
  "player": "{{user2}}"
}

### getting the active game for player 1
GET http://localhost:8081/tic-tac-toe/api/players/{{user1}}/playing