@user1=b85182a8-68f8-4d42-b0d5-6166bf2e8284
@user2=7ad223bd-bf5e-4945-8284-3a9c81e4e7a9


### starting a new match
POST http://localhost:8080/api/matches/
Content-Type: application/json

{
  "player1": "{{user1}}",
  "player2": "{{user2}}"
}

> {%
    client.global.set("gameId", response.body.id);
%}

### starting a new match against an ai
POST http://localhost:8080/api/matches/ai
Content-Type: application/json

{
  "player": "{{user1}}"
}

> {%
    client.global.set("gameId", response.body.id);
%}

### getting match
GET http://localhost:8080/api/matches/{{gameId}}


### making a move
PATCH http://localhost:8080/api/matches/{{gameId}}
Content-Type: application/json

{
  "x": 1,
  "y": 0,
  "player": "{{user1}}"
}

### making a counter move
PATCH http://localhost:8080/api/matches/{{gameId}}
Content-Type: application/json

{
  "x": 1,
  "y": 2,
  "player": "{{user2}}"
}

### making a move (not your turn)
PATCH http://localhost:8080/api/matches/{{gameId}}
Content-Type: application/json

{
  "x": 1,
  "y": 1,
  "player": "{{user2}}"
}

### making a move (occupied spot)
PATCH http://localhost:8080/api/matches/{{gameId}}
Content-Type: application/json

{
  "x": 0,
  "y": 1,
  "player": "{{user1}}"
}

### getting the active game for player 1
GET http://localhost:8080/api/players/{{user1}}/playing